### ISSUE TITLE
ERROR TRACEBAK

### ISSUE THREAD

**Issue by rodri2200** [Pymmdrza/EthereumMnemonicCrack#10]
Traceback (most recent call last):
  File "C:\Users\Rodrigo\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Rodrigo\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Rodrigo\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Rodrigo\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\mnemonic\EthereumMnemonicCrack-mainx\MneEthOn_V2.py", line 69, in <module>
    mmdrza()
  File "C:\Users\Rodrigo\Desktop\mnemonic\EthereumMnemonicCrack-mainx\MneEthOn_V2.py", line 44, in mmdrza
    res = respone_block.json()
  File "C:\Users\Rodrigo\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Pymmdrza** [comment]
Dear @rodri2200 ,

Thank you for bringing this issue to our attention. We appreciate your diligence in reporting potential problems.

After carefully reviewing the script you mentioned, it appears that the reported error is related to an issue with JSON decoding. The error message indicates that the script encountered difficulty in decoding JSON data, specifically, it was expecting a value at line 1, column 1, but did not find one.

This type of error commonly occurs when the script attempts to parse JSON data from a source, such as an API response, but the response is empty or not in the expected format. As a result, the JSON decoding process fails, leading to the reported error.

To address this issue, we recommend checking the source of the JSON data being parsed by the script. Ensure that the data source is providing valid JSON-formatted responses and that the script handles potential errors or empty responses gracefully to prevent similar issues in the future.

If you require further assistance or have any additional questions, please feel free to reach out. We are here to help.

Best regards,
@Pymmdrza

**Comment by rodri2200** [comment]
okay thank you very much, but how could I solve it since I am not very familiar with this, I am quite new

**Comment by Pymmdrza** [comment]
> okay thank you very much, but how could I solve it since I am not very familiar with this, I am quite new

Run This Script V3 on REPLIT: [RUN NOW](https://replit.com/@MrPyMmdrza/EthereumMnemonic-Checker?v=1 'Ethereum Mnemonic Checker V3')

if need running in your system : 

windows : 
```shell
pip install rich hdwallet requests-html
```

linux: 
```shell
pip3 install rich hdwallet requests-html
```

after install can running like that : 
- Windows:  `python MneEthOn_V3.py`
- Linux: `python3 MneEthOn_V3.py`

>[!NOTE]
>If you look carefully, you will see that for those who do not have any kind of talent, we have also put easy installation files for them so that we do not encounter such cases, but unfortunately, I still see that without reading anything, the project description page is just for convenience. You apply here.

- README -> [Installation](https://github.com/Pymmdrza/EthereumMnemonicCrack/tree/mainx#mnemonic-ethereum-generated-and-check-online-)
- README -> [Check Offline Detail's](https://github.com/Pymmdrza/EthereumMnemonicCrack/tree/mainx#mnemonic-ethereum-generated-and-check-offline-from-file-)
- INSTALL.bat (For Package's on Windows) -> [INSTALL.bat](https://github.com/Pymmdrza/EthereumMnemonicCrack/blob/mainx/01%20-%20INSTALL.bat)
- Runner (Runner File For After Install) -> [Runner.bat](https://github.com/Pymmdrza/EthereumMnemonicCrack/blob/mainx/02%20-%20Run%20(after%20install).bat)
