### ISSUE TITLE
hellow im back

### ISSUE THREAD

**Issue by rodri2202** [Pymmdrza/EthereumMnemonicCrack#15]
You know that everything was fine out of nowhere it closed and it started repeating that to me, I have the antivirus disabled so that nothing or that is not deleted. I don't know if it's my mistake, if so, sorry.

python: can't open file 'C:\\Users\\Rodrigo\\Desktop\\dasdsadasdas\\EthereumMnemonicCrack-mainx\\MneEthOn_V4_1.py': [Errno 2] No such file or directory

![error otro ais](https://github.com/Pymmdrza/EthereumMnemonicCrack/assets/163935329/d3f28d52-777c-4cea-8efa-67227011ead4)

**Comment by Pymmdrza** [comment]
```bash
git clone https://github.com/Pymmdrza/EthereumMnemonicCrack.git
cd EthereumMnemonicCrack
# windows :
Runner_V4_1.cmd
# linux :
chmod +x Runner_V4_1.sh&&./Runner_V4_1.sh
```
