### ISSUE TITLE
It does not print the mnemonic phrase from which it generates the private key

### ISSUE THREAD

**Issue by Prophet1984** [Pymmdrza/EthereumMnemonicCrack#2]
The correct console print should look like this:

┌───────────────── Ethereum Mnemonic Checker V3 ───────────────────┐
│ Total Checked: 152488  Win:0                                                                                                    │
│  Seed Phrase:         Example Example Example Example Example Example Example Example  │ 
│                                Example Example Example Example                                                           │
│ Addr:                      0x28a923bf479Fd09345eE22FFE0Ecb5C01329417e                                   │
│                                                                                                                                                    │
│                                                                                                                                                    │
│ PRIVATEKEY:  f012555bae8df53c68a06cd0cc8d66bcaf2dd56663b15910e134c65eb95eaf78   │
│                                                                                                                                                    │
│                                                                                                                                                    │
└────────────────────  Mmdrza.Com  ───────────────────────────┘

**Comment by Pymmdrza** [comment]
> The correct console print should look like this:
> 
> ┌───────────────── Ethereum Mnemonic Checker V3 ───────────────────┐ │ Total Checked: 152488 Win:0 │ │ Seed Phrase: Example Example Example Example Example Example Example Example │ │ Example Example Example Example │ │ Addr: 0x28a923bf479Fd09345eE22FFE0Ecb5C01329417e │ │ │ │ │ │ PRIVATEKEY: f012555bae8df53c68a06cd0cc8d66bcaf2dd56663b15910e134c65eb95eaf78 │ │ │ │ │ └──────────────────── Mmdrza.Com ───────────────────────────┘



> 

i insert just private key and address with eth value and transactions . mnemonic no need to print . 


```
 bip44_hdwallet.from_mnemonic(mnemonic=MNEMONIC, passphrase=PASSPHRASE, language=LANGUAGE)

```
