### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by 13178262626** [Pymmdrza/EthereumMnemonicCrack#5]
File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1640, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')

During handling of the above exception, another exception occurred:
I keep getting this error and I don't know how to fix it
![20230105173219](https://user-images.githubusercontent.com/23096248/210747667-9c1c575e-102f-4081-8e5f-dfda4a0db80c.png)

**Comment by Pymmdrza** [comment]
> File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake self._raise_ssl_error(self._ssl, result) File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1640, in _raise_ssl_error raise SysCallError(-1, "Unexpected EOF") OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
> 
> During handling of the above exception, another exception occurred: I keep getting this error and I don't know how to fix it ![20230105173219](https://user-images.githubusercontent.com/23096248/210747667-9c1c575e-102f-4081-8e5f-dfda4a0db80c.png)

problem from your internet network
