### ISSUE TITLE
SyntaxError: unmatched

### ISSUE THREAD

**Issue by cryptosaver** [Pymmdrza/EthereumMnemonicCrack#7]
python MneEthOn_V3.py
  File "/home/runner/EthereumMnemonicCrack-2/MneEthOn_V3.py", line 69
    addr) + '[/]\nPRIVATEKEY: [grey54]' + str(priv) + '[/]')
                                                           ^
SyntaxError: unmatched ')'

**Comment by Pymmdrza** [comment]
> @cryptosaver @Pymmdrza yeah nothing works ![image](https://user-images.githubusercontent.com/64865096/265922540-bb76a461-da45-4048-8ba9-09877137de89.png)

```
pip install hdwallet
pip install lxml
pip install rich
pip install mnemonic
pip install requests-html

```

@YashvirGaming & @cryptosaver Before posting any wrong comment, first read the [main page](https://github.com/Pymmdrza/EthereumMnemonicCrack#readme) and the description and then post a comment. No, like uncultured people, you don't value work and want everything ready.

 [Ethereum Mnemonic Crack - Main Page](https://github.com/Pymmdrza/EthereumMnemonicCrack#readme)

**Comment by Pymmdrza** [comment]
> @Pymmdrza 
> Also as your requirements im sure i already installed them 3 times already
> cuz im getting Already satisfied.
> 
> 
> I run your 1. INSTAL.bat (batch file)
> 
> ![image](https://github.com/Pymmdrza/EthereumMnemonicCrack/assets/64865096/53faa439-221e-4abf-afc7-827970d5fa0a)
> 
> So can you fix the scripts
> Why does it LOOP though ?
> Loop until it crashes it kinda open over 500+ cmd's tabs lol 
> 

Remove & check again.
